// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedShipmentChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedShipmentChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201811230948090_Added Shipment Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
