// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ValidationAttributeChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationAttributeChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201811230910475_Validation Attribute Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
